/**
 * src/icons/carbon.ts
 *
 * ── THE ICON MAP ───────────────────────────────────────────────────────────
 * Single source of truth for every icon in the app. Screens and config objects
 * reference a SEMANTIC KEY ('medication', 'overdue'), never a vendor icon name —
 * so re-pointing an icon, or swapping icon libraries again, is a one-line change
 * here instead of a find-and-replace across 19 files.
 *
 * Two groups:
 *   appIcons     — the app's own vocabulary (nav, clinical, commerce, status…).
 *   vuetifyAliases — Vuetify's INTERNAL slots (checkboxOn, prev, ratingFull…).
 *                  Vuetify renders these itself for v-checkbox, v-pagination,
 *                  v-rating, v-select, etc. They must all be present or those
 *                  components render nothing. The Carbon choices are lifted from
 *                  Vuetify's own iconsets/carbon.js, which picks via UnoCSS
 *                  classes (`i-carbon:*`); this project has no UnoCSS, so the
 *                  same choices resolve through @carbon/icons-vue components.
 *
 * WHY THE `24` VARIANTS: Carbon ships each glyph at 16/20/24/32. 24 is Vuetify's
 * default icon size, so at default density the glyph is pixel-exact. AppIcon then
 * renders it at width/height 1em, so Vuetify's existing font-size-based sizing
 * (`size="small"`, `size="32"`, surrounding font-size) keeps driving the real
 * size exactly as the MDI webfont did. Carbon svgs carry fill="currentColor", so
 * every existing color class / `color` prop keeps working untouched.
 */

/*
 * ⚠️ ONE DEEP IMPORT, deliberately. `@carbon/icons-vue`'s barrel exports the
 * name `Copy24` TWICE — from `copy/24` and from `image--copy/24` — which makes
 * the binding ambiguous, so TypeScript reports it as not exported at all. The
 * icon itself is fine; only the barrel is. Importing the module directly gets
 * the plain copy glyph unambiguously. Everything else comes from the barrel as
 * usual; revisit if the package fixes the duplicate.
 */
import Copy24 from '@carbon/icons-vue/es/copy/24.js'

import {
  CicsExplorer24,
  ThumbsDown24,
  ThumbsUp24,
  FileStorage24,
  Network_424,
  ScisControlTower24,
  Activity24,
  Add24,
  AddAlt24,
  Ai24,
  AiGenerate24,
  Apps24,
  ArrowDown24,
  ArrowDownRight24,
  ArrowLeft24,
  ArrowRight24,
  ArrowUp24,
  ArrowUpRight24,
  ArrowsVertical24,
  At24,
  Attachment24,
  Calendar24,
  Bot24,
  CalendarHeatMap24,
  CalendarTools24,
  Camera24,
  CaretDown24,
  CaretRight24,
  ChartLine24,
  ChartLineData24,
  ChartNetwork24,
  ChartRelationship24,
  Chat24,
  Checkbox24,
  CheckboxCheckedFilled24,
  CheckboxIndeterminateFilled24,
  Checkmark24,
  CheckmarkFilled24,
  CheckmarkOutline24,
  Chemistry24,
  ChevronDown24,
  ChevronLeft24,
  ChevronRight24,
  ChevronSort24,
  ChevronUp24,
  CircleDash24,
  CircleFilled24,
  Close24,
  CloseFilled24,
  CloudUpload24,
  ColorPalette24,
  Dashboard24,
  DeliveryTruck24,
  Document24,
  DocumentBlank24,
  DocumentTasks24,
  Download24,
  Edit24,
  Email24,
  EventSchedule24,
  Eyedropper24,
  FaceSatisfied24,
  FavoriteFilled24,
  Filter24,
  Flag24,
  FlowConnection24,
  Folder24,
  Group24,
  Growth24,
  HealthCross24,
  Help24,
  Home24,
  Hospital24,
  Idea24,
  Identification24,
  Information24,
  Keyboard24,
  Launch24,
  ListChecked24,
  Locked24,
  Logout24,
  MacCommand24,
  MacOption24,
  MacShift24,
  Maximize24,
  Medication24,
  Menu24,
  MeterAlt24,
  MicrophoneFilled24,
  Minimize24,
  Misuse24,
  Moon24,
  Notification24,
  NotificationFilled24,
  NotificationNew24,
  OverflowMenuHorizontal24,
  Package24,
  PageFirst24,
  PageLast24,
  Pause24,
  Phone24,
  Pills24,
  Play24,
  PlayFilled24,
  ProgressBarRound24,
  RadioButton24,
  RadioButtonChecked24,
  RainDrop24,
  RecentlyViewed24,
  Renew24,
  Repeat24,
  ReportData24,
  Restaurant24,
  Return24,
  Rocket24,
  Ruler24,
  Save24,
  Scales24,
  Search24,
  Security24,
  SendFilled24,
  Settings24,
  SettingsAdjust24,
  ShoppingCart24,
  SidePanelClose24,
  SidePanelOpen24,
  SkillLevelAdvanced24,
  SkillLevelBasic24,
  SkillLevelIntermediate24,
  Star24,
  StarFilled24,
  StarHalf24,
  Stethoscope24,
  Store24,
  Subtract24,
  Sun24,
  Tag24,
  TextFont24,
  Time24,
  TimeFilled24,
  Timer24,
  Translate24,
  Undo24,
  Unlink24,
  User24,
  UserFollow24,
  UserMultiple24,
  UpToTop24,
  Video24,
  View24,
  ViewOff24,
  VolumeDown24,
  VolumeMute24,
  VolumeUp24,
  Wallet24,
  Warning24,
  WarningFilled24,
  ZoomIn24,
  ZoomOut24,
} from '@carbon/icons-vue'

// Custom glyphs with no Carbon equivalent — same contract (1em, currentColor).
import OfflineBolt from './OfflineBolt.vue'

/** The app's own icon vocabulary. Keys are semantic, not vendor names. */
export const appIcons = {
  activity: Activity24,
  agent: Bot24,
  ai: Ai24,
  aiGenerate: AiGenerate24,
  alert: Warning24,
  alertFilled: WarningFilled24,
  arrowLeft: ArrowLeft24,
  arrowRight: ArrowRight24,
  at: At24,
  attachment: Attachment24,
  calendar: Calendar24,
  calendarCheck: CalendarTools24,
  calendarRange: CalendarHeatMap24,
  calendarTime: EventSchedule24,
  camera: Camera24,
  cardiac: Activity24,
  caretRight: CaretRight24,
  cart: ShoppingCart24,
  chartLine: ChartLine24,
  chartTrend: ChartLineData24,
  chat: Chat24,
  // Graph vocabulary: the knowledge graph itself, its two canvas view modes, and
  // the "this entity has no relationships yet" state.
  graph: ChartRelationship24,
  graphClusters: FlowConnection24,
  graphNetwork: ChartNetwork24,
  /** Carbon "network--4". */
  network4: Network_424,
  /** Carbon "IBM CICS Explorer" — the rail's Insights KPI mark. */
  cicsExplorer: CicsExplorer24,
  /** Carbon "IBM Supply Chain Intelligence Suite Control Tower" ("scis--control-tower")
   *  — the rail's Entities KPI mark. */
  scisControlTower: ScisControlTower24,
  /**
   * The rail's Sources KPI mark. Carbon ships no "file system" glyph in this
   * package version — "file-storage" is the closest match and stands in.
   */
  fileSystem: FileStorage24,
  unlink: Unlink24,
  check: Checkmark24,
  checkAll: CheckmarkOutline24,
  checkCircle: CheckmarkOutline24,
  checkFilled: CheckmarkFilled24,
  chevronDown: ChevronDown24,
  chevronLeft: ChevronLeft24,
  chevronRight: ChevronRight24,
  clinic: Hospital24,
  clock: Time24,
  close: Close24,
  copy: Copy24,
  creditCard: Wallet24,
  dashboard: Dashboard24,
  document: Document24,
  dot: CircleFilled24,
  dotOutline: CircleDash24,
  download: Download24,
  edit: Edit24,
  email: Email24,
  emoji: FaceSatisfied24,
  externalLink: Launch24,
  favoriteFilled: FavoriteFilled24,
  filter: Filter24,
  flag: Flag24,
  folder: Folder24,
  formatText: TextFont24,
  goal: Growth24,
  help: Help24,
  history: RecentlyViewed24,
  home: Home24,
  hydration: RainDrop24,
  idCard: Identification24,
  info: Information24,
  injection: Medication24,
  lab: Chemistry24,
  // Rising-bar "skill level" glyphs, used as a 3-step level indicator (1/2/3 bars).
  levelLow: SkillLevelBasic24,
  levelMedium: SkillLevelIntermediate24,
  levelHigh: SkillLevelAdvanced24,
  logout: Logout24,
  medicalKit: HealthCross24,
  medication: Medication24,
  menu: Menu24,
  messages: Chat24,
  meter: MeterAlt24,
  // Filled glyphs: the composer's mic and send read as solid marks, not outlines.
  microphone: MicrophoneFilled24,
  minus: Subtract24,
  night: Moon24,
  notes: ListChecked24,
  notification: Notification24,
  notificationFilled: NotificationFilled24,
  notificationNew: NotificationNew24,
  nutrition: Restaurant24,
  overdue: TimeFilled24,
  overflow: OverflowMenuHorizontal24,
  package: Package24,
  phone: Phone24,
  pill: Pills24,
  plus: Add24,
  plusCircle: AddAlt24,
  progress: ProgressBarRound24,
  records: DocumentTasks24,
  recordsEmpty: DocumentBlank24,
  recordsHistory: RecentlyViewed24,
  recordsReview: ReportData24,
  refresh: Renew24,
  repeat: Repeat24,
  rocket: Rocket24,
  ruler: Ruler24,
  save: Save24,
  panelCollapse: SidePanelClose24,
  panelExpand: SidePanelOpen24,
  search: Search24,
  send: SendFilled24,
  settings: Settings24,
  shieldCheck: Security24,
  shieldLock: Locked24,
  shipping: DeliveryTruck24,
  sort: ArrowsVertical24,
  star: Star24,
  stethoscope: Stethoscope24,
  store: Store24,
  sun: Sun24,
  tag: Tag24,
  timer: Timer24,
  tip: Idea24,
  thumbsUp: ThumbsUp24,
  thumbsDown: ThumbsDown24,
  // Circled lightning bolt — token / energy counts (TokensBadge). Custom svg:
  // Carbon has no circled bolt, only bare `lightning` / `flash--filled`.
  tokens: OfflineBolt,
  translate: Translate24,
  trendDown: ArrowDownRight24,
  trendUp: ArrowUpRight24,
  tune: SettingsAdjust24,
  unfold: ChevronSort24,
  upToTop: UpToTop24,
  user: User24,
  userAdd: UserFollow24,
  userGroup: Group24,
  userMultiple: UserMultiple24,
  video: Video24,
  view: View24,
  viewOff: ViewOff24,
  vitals: Activity24,
  weight: Scales24,
  widgets: Apps24,
  zoomIn: ZoomIn24,
  zoomOut: ZoomOut24,
} as const

/**
 * Vuetify's internal icon slots. Vuetify looks these up by name when it renders
 * its own chrome — omit one and that component silently loses its icon.
 */
export const vuetifyAliases = {
  collapse: ChevronUp24,
  complete: Checkmark24,
  cancel: CloseFilled24,
  close: Close24,
  delete: CloseFilled24,
  clear: CloseFilled24,
  success: CheckmarkFilled24,
  info: Information24,
  warning: Warning24,
  error: Misuse24,
  prev: ChevronLeft24,
  next: ChevronRight24,
  checkboxOn: CheckboxCheckedFilled24,
  checkboxOff: Checkbox24,
  checkboxIndeterminate: CheckboxIndeterminateFilled24,
  delimiter: CircleFilled24,
  sortAsc: ArrowUp24,
  sortDesc: ArrowDown24,
  expand: ChevronDown24,
  menu: Menu24,
  subgroup: CaretDown24,
  dropdown: ChevronDown24,
  radioOn: RadioButtonChecked24,
  radioOff: RadioButton24,
  edit: Edit24,
  ratingEmpty: Star24,
  ratingFull: StarFilled24,
  ratingHalf: StarHalf24,
  loading: Renew24,
  first: PageFirst24,
  last: PageLast24,
  unfold: ChevronSort24,
  file: Attachment24,
  plus: Add24,
  minus: Subtract24,
  calendar: Calendar24,
  treeviewCollapse: ChevronDown24,
  treeviewExpand: ChevronRight24,
  tableGroupExpand: ChevronRight24,
  tableGroupCollapse: ChevronDown24,
  eyeDropper: Eyedropper24,
  upload: CloudUpload24,
  color: ColorPalette24,
  command: MacCommand24,
  ctrl: Keyboard24,
  space: Keyboard24,
  shift: MacShift24,
  alt: MacOption24,
  enter: Return24,
  arrowup: ArrowUp24,
  arrowdown: ArrowDown24,
  arrowleft: ArrowLeft24,
  arrowright: ArrowRight24,
  backspace: Undo24,
  play: Play24,
  playFilled: PlayFilled24,
  pause: Pause24,
  fullscreen: Maximize24,
  fullscreenExit: Minimize24,
  volumeHigh: VolumeUp24,
  volumeMedium: VolumeDown24,
  volumeLow: VolumeDown24,
  volumeOff: VolumeMute24,
  search: Search24,
} as const

/** Every resolvable icon name: the app vocabulary plus Vuetify's internal slots. */
export const icons = { ...appIcons, ...vuetifyAliases }

/** Valid `name` for <app-icon>, and valid string for any Vuetify icon prop. */
export type AppIconName = keyof typeof appIcons
export type IconName = keyof typeof icons
