/**
 * src/types/carbon-pictograms.d.ts
 *
 * @carbon/pictograms ships NO type declarations. Unlike @carbon/icons-vue (which
 * exports ready-made Vue COMPONENTS), the base pictograms package exports plain
 * DESCRIPTOR objects — `{ elem, attrs, content }` trees generated by Carbon's
 * icon-build-helpers — under `@carbon/pictograms/es/<name>`. There is no official
 * `@carbon/pictograms-vue`, so we consume those descriptors directly and render
 * them ourselves in AppPictogram.vue.
 *
 * This declares the shape of a descriptor and the wildcard subpath module so the
 * deep `es/*` imports in src/icons/pictograms.ts type-check under strict config
 * instead of landing as implicit `any`. The single-source-of-truth guard is the
 * same as the icon map: pictograms.ts is the ONLY place that imports these paths,
 * and AppPictogram warns (never throws/blanks) on an unknown semantic key.
 */
declare module '@carbon/pictograms/es/*' {
  const descriptor: import('@/icons/pictograms').PictogramNode
  export default descriptor
}
